# -------------------------------------------------------------------------------------------
#  Copyright (c) 2024.  SupportVectors AI Lab
#
#  This code is part of the AI Lab Book companion repository.
#  It is released under the MIT License - see the LICENSE file at the repository root.
#
#  Copyright (c) 2016-2026 SupportVectors AI Lab.
#
#  Author: SupportVectors AI Training
# -------------------------------------------------------------------------------------------

"""A simple glossary builder module that uses an OpenAI-hosted model to generate basic glossaries.

This module provides a naive implementation of a glossary builder that uses an LLM
to generate simple glossaries. It reads prompts from markdown files and uses them to guide the
model in generating glossary content.

The module requires an OpenAI API key to be set in the environment variables.
"""

from pathlib import Path
import os

from openai import OpenAI
from svlearn.common.utils import check_valid_file
from loguru import logger
from prompts import config
from dotenv import load_dotenv

# Needed for loading env variables (including the OPEN API KEY from .env)
load_dotenv(override=True)
# LLM endpoint options:
#  (a) OpenAI hosted (default): LLM_MODEL=gpt-5-mini, OPENAI_API_KEY required
#  (b) self-hosted OpenAI-compatible server (vLLM / Ollama): set OPENAI_BASE_URL
#      (read natively by the OpenAI client, e.g. http://localhost:11434/v1) and a
#      served model, e.g. LLM_MODEL="llama3.1"
LLM_MODEL = os.getenv("LLM_MODEL", "gpt-5-mini")

# -------------------------------------------------------------------------------------------


class NaiveGlossaryBuilder:
    """A simple glossary builder that creates glossaries using an LLM.
    
    This class provides a basic implementation for generating glossaries by making API calls
    to the configured model. It uses predefined prompts stored in markdown files to guide
    the model in generating appropriate glossary content.
    
    Attributes:
        __PROMPT_FILE_NAME (str): The path to the prompt file relative to the current working directory.
    """

    __PROMPT_FILE_NAME = "prompts/00_naive_glossary_prompt.md"
    
    def build(self) -> str:
        """Build a glossary with a few terms. For this, it invokes the OpenAI API,
        using a simple text prompt. In other words, it makes a call to the configured
        model, asking it to generate a glossary for the given subject.
        
        **Note**: Ensure that your OpenAI API key is set in the environment variable.

        Args:
            subject: A string representing the subject of the glossary.

        Returns:
            A string representing the glossary generated by the OpenAI API.
        """

        
        file = Path.cwd() / self.__PROMPT_FILE_NAME
        logger.info(f"Reading prompt from file: {file}")
        
        check_valid_file(str(file))

        prompt = file.read_text(encoding="utf-8")

        # Call the OpenAI API to generate the glossary
        api = OpenAI(base_url=os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"))
        response = api.chat.completions.create(model=LLM_MODEL, 
                                               messages=[{"role": "system", "content": prompt}])

        return response.choices[0].message.content or ""

# -------------------------------------------------------------------------------------------
if __name__ == "__main__":
    glossary = NaiveGlossaryBuilder().build()
    results_dir = config["paths"]["results_dir"]
    Path(results_dir).mkdir(parents=True, exist_ok=True)
    output_file = Path(f"{results_dir}/simple_glossary.md")
    output_file.write_text(glossary, encoding="utf-8")
    print(glossary)